spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pos.cdso6eyswiwz.ap-northeast-2.rds.amazonaws.com:5432/fake_hunters
    username: pos   # ⚠️ 실제 RDS 유저명으로 교체
    password: pospos2026^P       # ⚠️ 실제 비밀번호

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: fakehunters.backend
  type-handlers-package: fakehunters.backend.global.mybatis
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl